# Generated by Django 5.2.6 on 2025-09-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
