# Generated by Django 5.2.6 on 2025-09-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_post_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(upload_to='post_videos/'),
        ),
    ]
