# Generated by Django 5.2.6 on 2025-09-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='like',
            new_name='follow',
        ),
    ]
