# Generated by Django 5.2.6 on 2026-04-12 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_profile_about_alter_profile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTExam',
            fields=[
                ('exam_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('english', 'English'), ('chemistry', 'Chemistry')], default='mathematics', max_length=30)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=20)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(choices=[('distinction', 'Distinction'), ('credit', 'Credit'), ('pass', 'Pass'), ('nearly', 'Nearly'), ('fail', 'Fail')], default='fail', max_length=20)),
                ('time_used_sec', models.PositiveIntegerField(default=0)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='CBTScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
