# Generated by Django 5.2.6 on 2026-04-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_livesession_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtexam',
            name='subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('english', 'English'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('economics', 'Economics'), ('government', 'Government'), ('accounting', 'Accounting'), ('geography', 'Geography')], default='mathematics', max_length=30),
        ),
    ]
