# Generated by Django 5.2.6 on 2026-04-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_cbtexam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='class_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
