# Generated by Django 5.2.6 on 2026-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_profile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='livesession',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
