# Generated by Django 5.2.6 on 2026-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_classpost_classpostcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpostcomment',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='comment_audio/'),
        ),
        migrations.AddField(
            model_name='classpostcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
        migrations.AlterField(
            model_name='classpostcomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
