# Generated by Django 5.2.6 on 2026-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_classpostcomment_audio_classpostcomment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtexam',
            name='subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics')], default='mathematics', max_length=30),
        ),
    ]
