# Generated by Django 5.2.6 on 2026-05-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_cbtexam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='class_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='school.classpost'),
        ),
    ]
