# Generated by Django 5.2.6 on 2026-05-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_notification_class_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics')], default='mathematics', max_length=30)),
                ('topic_key', models.CharField(max_length=80)),
                ('topic_name', models.CharField(blank=True, max_length=200)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subject', 'section', 'topic_key'],
                'unique_together': {('user', 'subject', 'topic_key')},
            },
        ),
    ]
